### ISSUE TITLE
我又来了

### ISSUE THREAD

**Issue by xinyihl** [Pasuu/Modpack.siteweb#6]
老样子还是发个附件[demo.zip](https://github.com/Pasuu/Modpack.siteweb/files/12429396/demo.zip)
用FastAPI搞了一个零时的下载量，没有持久化数据的代码关了数据就没了，也没有什么校验功能
还有老版本的下载方式
![QQ截图20230824203057](https://github.com/Pasuu/Modpack.siteweb/assets/75861358/f888dba8-7cac-4bb1-9a68-739624facea5)
另外的话加个qq？

**Comment by Pasuu** [comment]
QQ是206487905，不过我在上学，这些比较麻烦的部分要等放假了。

**Comment by xinyihl** [comment]
我给网站重写了一下，这个是测试的站点
http://test.mctist.top/
